### ISSUE TITLE
Beautiful!

### ISSUE THREAD

**Issue by spences10** [LJNGDAHL/portfolio#1]
I love it 👌 

Can you explain what the other frameworks are for please?

**Comment by LJNGDAHL** [comment]
I am glad you liked it! 🎉  The portfolio mostly is built as a learning experience, so I wanted to try out a bunch of stuff just for the fun of it. Below, I have tried to summarise what I used in this project and why, but just give me another holler if you have any more questions that I didn't address.

## Next.js as an alternative to Create-React-App
Being fairly new to working with React, I have used `create-react-app` in my earlier projects, just to get started without having to worry about tooling. I wanted to use`Next.js` in this project both to compare it to `create-react-app`, but also because I was interested in how they had solved the server-side rendering bits. I really like other products by [Zeit](https://github.com/zeit/), the organization behind `Next.js` – especially the way deployment is made easy using [Now](https://zeit.co/now). Overall, I really enjoyed Next.js! 

## Redux just to learn it
I have not used `Redux` before, and, in all fairness, it felt a bit like overdoing it using Redux in this small project, but this I did just for the learning experience. I really see the benefit of using Redux in larger projects, but in small ones like this one, using React's own state would do just as fine.

## Prismic.io instead of, say like, Wordpress
I've never been a big fan of Wordpress, especially from a developer's point of view. And after hearing so many good things about `prismic.io`, I felt I needed to give it a try. And jeez, I am glad I did! 🙌  

I really like that `prismic.io` is API-based, making it extremely easy to work with. The configuration process of customising the dashboard was smooth and very intuitive. If you haven't tried working with [Prismic](https://prismic.io/), I really recommend giving it a try.

**Comment by spences10** [comment]
Wow, cool, thanks for the detail...

I think it was Prismic.io I was wondering what it was for, surprised I have never heard of it before

I'm playing around with Gatsby for my blog and for my personal site, something that doesn't suck will be fine 🙃 I have three or so branches all with different technologies, I have settled on `next` too as I like the `Link` function built in, no need to mess around with Redux then

Feel free to close the issue @LJNGDAHL I was just curious 

Thanks again 😄

**Comment by LJNGDAHL** [comment]
No worries! ⚡️  I think [Contentful](https://www.contentful.com/) is probably also worth checking out when it comes to CMS (I haven't had time to play with it yet), but I totally hear you – sometimes something that doesn't suck is good enough. I will definitely fiddle around with `Prismic`as soon as possible. 

All the best! ✨
